apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-game-depl
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: mihikadhariwal/dice-game
---
apiVersion: v1
kind: Service
metadata:
  name: dice-game-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
